
import Header2 from '@/components/Header2'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


   
  return (
    <html lang="fr">
      <body className="relative">
       
       
    <Header2 />
    {children}
    <Footer/>




      </body>
    </html>
  )
}
